eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/
  instance:
    instance-id: hrm-course-service
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:cn/yangcode/hrm/mapper/*Mapper.xml
  type-aliases-package: cn.yangcode.hrm.domain,cn.yangcode.hrm.query
server:
  port: 2030
spring:
  application:
    name: hrm-course-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///hrm-course
    username: root
